/**
 * Emits ONLY the role_permissions grant matrix as SQL, so it can be pasted into
 * the Supabase SQL editor without a DB password and without touching any other
 * seeded table (unlike emit-core-seed-sql.mts, which re-emits everything).
 *
 * Use when a new account role or a new module is added and the live matrix
 * needs to catch up. Idempotent: every row is an upsert on (role_id, module, action).
 *
 * Run: npx tsx scripts/db/emit-role-permissions-seed-sql.mts
 * Output: supabase/seed/0004_role_permissions_seed.sql
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { getModules, getDefaultPermissions, ROLE_KEYS } from "@/lib/mock-data/users";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const s = (v: string) => `'${v.replace(/'/g, "''")}'`;
const b = (v: boolean) => (v ? "true" : "false");

const perms = getDefaultPermissions();
const modules = getModules();
const actions = ["view", "create", "edit", "delete"] as const;

const out: string[] = [];
out.push(
  `-- role_permissions grant matrix (${ROLE_KEYS.length} roles × ${modules.length} modules × ${actions.length} actions = ${ROLE_KEYS.length * modules.length * actions.length} rows)`,
  "-- Generated by scripts/db/emit-role-permissions-seed-sql.mts - do not edit by hand.",
  "",
);

for (const role of ROLE_KEYS) {
  for (const m of modules) {
    const g = perms[role][m.key];
    for (const action of actions) {
      out.push(
        `insert into public.role_permissions (role_id, module, action, granted) values (${s(role)},${s(m.key)},${s(action)},${b(g[action])}) on conflict (role_id, module, action) do update set granted = excluded.granted;`,
      );
    }
  }
}

out.push("", "select count(*) as role_permission_rows from public.role_permissions;");

const dest = join(root, "supabase/seed/0004_role_permissions_seed.sql");
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out.join("\n") + "\n");
console.log(
  `Wrote ${dest} - ${ROLE_KEYS.length} roles × ${modules.length} modules × ${actions.length} actions`,
);
