-- Distinct chip colours for every shift template (26 rows, strategy: spread).
-- Generated by scripts/db/emit-shift-template-colors-sql.mts - do not edit by hand.
-- Safe to re-run: each statement targets one id and only touches colour columns.

update public.shift_templates set color = '#8A5A00', tint = '#FDF0D0', border = '#EBCF8A' where id = 'sh-1784041188782';  -- Amber · TL: 6:45 - 15:15
update public.shift_templates set color = '#5F44A8', tint = '#E9E2FA', border = '#BFB0E6' where id = 'sh-1784044728963';  -- Violet · TL: Sen 6:45 - 15:15
update public.shift_templates set color = '#3B6B25', tint = '#E1F1D4', border = '#AED697' where id = 'sh-1784040760120';  -- Green · TL: 8:00 - 15:30
update public.shift_templates set color = '#8F3E19', tint = '#FCE3D5', border = '#F0B393' where id = 'sh-1784043747532';  -- Orange · TL: 8:00 - 22:45
update public.shift_templates set color = '#33468F', tint = '#DFE4F8', border = '#AEB9E6' where id = 'sh-1784044756583';  -- Indigo · TL: 15:00-22:30
update public.shift_templates set color = '#5F5E0E', tint = '#F2F2CE', border = '#D4D389' where id = 'sh-1784040782857';  -- Olive · TL: 16:15 - 22:45
update public.shift_templates set color = '#A3342F', tint = '#FBDEDB', border = '#EFAFA9' where id = 'sh-1784043969968';  -- Brick · TL: Night shift
update public.shift_templates set color = '#1F5E96', tint = '#D9E9F8', border = '#9CC4E5' where id = 'sh-1784045870676';  -- Blue · 6:30 - 10:00
update public.shift_templates set color = '#74513A', tint = '#F0E4DB', border = '#D2B7A5' where id = 'sh-1784046106812';  -- Coffee · 6:45 - 15:15
update public.shift_templates set color = '#A33064', tint = '#FCDFEB', border = '#F0AECB' where id = 'sh1';  -- Rose · M = 6:45- 15:15
update public.shift_templates set color = '#0F6274', tint = '#D5EDF2', border = '#93CBD6' where id = 'sh2';  -- Teal · Morning + Stock
update public.shift_templates set color = '#4A5560', tint = '#E4E8EC', border = '#B4BDC5' where id = 'sh-1784043857982';  -- Slate · Sen = 6:45 - 15:15
update public.shift_templates set color = '#83398C', tint = '#F6DFF7', border = '#DCAEE2' where id = 'sh-1784036743191';  -- Plum · KH
update public.shift_templates set color = '#0E6350', tint = '#D6F0E7', border = '#96D5C1' where id = 'sh-1784474750793';  -- Emerald · CO =. 8:00 - 16:30
update public.shift_templates set color = '#8A5A00', tint = '#F8E3AE', border = '#DDBB63' where id = 'sh6';  -- Amber (deep) · Team Leader
update public.shift_templates set color = '#5F44A8', tint = '#DCD1F4', border = '#A797DA' where id = 'sh-1784036716147';  -- Violet (deep) · Chef
update public.shift_templates set color = '#3B6B25', tint = '#CDE8B9', border = '#93C776' where id = 'sh4';  -- Green (deep) · Evening (split)
update public.shift_templates set color = '#8F3E19', tint = '#F8D0BA', border = '#E29A72' where id = 'sh-1784043919010';  -- Orange (deep) · 11:30 - 20:00
update public.shift_templates set color = '#33468F', tint = '#CBD4F2', border = '#93A2DC' where id = 'sh-1784179473878';  -- Indigo (deep) · 12:30 - 21:00
update public.shift_templates set color = '#5F5E0E', tint = '#E8E7B0', border = '#C2C165' where id = 'sh-1784858624440';  -- Olive (deep) · 13:30 -22:00
update public.shift_templates set color = '#A3342F', tint = '#F7C8C3', border = '#E29089' where id = 'sh-1784046656477';  -- Brick (deep) · 14:45 - 23:15
update public.shift_templates set color = '#1F5E96', tint = '#C2DCF3', border = '#7FADDA' where id = 'sh3';  -- Blue (deep) · A = 14:45 - 22:15
update public.shift_templates set color = '#74513A', tint = '#E5D2C4', border = '#C09E88' where id = 'sh-1784043897216';  -- Coffee (deep) · Sen 14:45 - 23:15
update public.shift_templates set color = '#A33064', tint = '#F8C9DD', border = '#E48FB5' where id = 'sh-1784036788068';  -- Rose (deep) · KH: 16:00 - 19:00
update public.shift_templates set color = '#0F6274', tint = '#BCE1EA', border = '#71B7C6' where id = 'sh-1784043805474';  -- Teal (deep) · N = 22:45 - 7:15
update public.shift_templates set color = '#4A5560', tint = '#D3DAE0', border = '#9BA6B1' where id = 'sh5';  -- Slate (deep) · Night

select id, name, color, tint, border from public.shift_templates order by color, name;
