-- CliffyHill supply catalogue for wesley, transcribed from the home's stocktake sheet.
-- Generated by scripts/db/emit-cliffyhill-stock-seed-sql.mts - do not edit by hand.
-- Replaces the demo catalogue seeded by 0002_stock_seed.sql.
-- Prices are EXCL GST (orders total on total_excl_gst). Par levels are DERIVED,
-- not supplied by the home - see the script header.

-- Clear the demo catalogue for this building. Products cascade to stock_levels,
-- stock_movements and order_lines; orders/providers are cleared explicitly.
delete from public.order_lines where order_id in (select id from public.orders where building_id = 'wesley');
delete from public.orders where building_id = 'wesley';
delete from public.stock_movements where building_id = 'wesley';
delete from public.products where building_id = 'wesley';
delete from public.stock_levels where building_id = 'wesley';
delete from public.providers where building_id = 'wesley';

insert into public.providers (id, building_id, name, category, contact_email, phone, lead_time, terms, preferred, color, tint) values
  ('cliffyhill','wesley','CliffyHill','Other',null,null,null,null,true,'#2C3563','#E4E6F2')
on conflict (id) do update set name = excluded.name, category = excluded.category, preferred = excluded.preferred,
  color = excluded.color, tint = excluded.tint;

insert into public.products (id, building_id, name, category, unit, price, provider_id, par) values
  ('grb2-5','wesley','GREEN RHINO Toilet Disinfectant Cleaner 5L','Housekeeping','bottle (5L)',26.80,'cliffyhill',5),
  ('grk4-20','wesley','GREEN RHINO Auto Dishwasher Detergent 20L','Housekeeping','can (20L)',104.60,'cliffyhill',5),
  ('grs4-5','wesley','GREEN RHINO Enviro Foaming Hand Soap 5L','Housekeeping','bottle (5L)',26.88,'cliffyhill',5),
  ('grs6-5','wesley','GREEN RHINO Body & Hair Shampoo 5L','Housekeeping','bottle (5L)',26.80,'cliffyhill',5),
  ('grs8f-5','wesley','GREEN RHINO Foaming Hand Sanitiser 5L','Clinical & PPE','bottle (5L)',26.80,'cliffyhill',5),
  ('hipi','wesley','Cabernet Franc Malbec 2022','Kitchen & Nutrition','bottle',16.00,'cliffyhill',5),
  ('igc-0004','wesley','IngoCare Pullups - Size M','Continence','bag of 16',13.12,'cliffyhill',5),
  ('igc-0005','wesley','IngoCare Pullups - Size L','Continence','bag of 16',14.40,'cliffyhill',15),
  ('igc-0006','wesley','IngoCare Pullups - Size XL','Continence','bag of 16',15.52,'cliffyhill',20),
  ('igc-0010','wesley','IngoCare Wraps/All-In-One Premium - Size M','Continence','bag of 12',13.20,'cliffyhill',5),
  ('igc-0012','wesley','IngoCare Wraps/All-In-One Premium - Size XL','Continence','bag of 12',16.08,'cliffyhill',5),
  ('igc-0013','wesley','IngoCare Insert Pad - Size L','Continence','bag of 16',9.50,'cliffyhill',5),
  ('sanitary-pads','wesley','Sanitary pads','Continence',null,0.00,'cliffyhill',5),
  ('igc-12350','wesley','Nitrile Sky Blue Gloves Size S','Clinical & PPE','carton of 10 packs',45.00,'cliffyhill',5),
  ('igc-12351','wesley','Nitrile Sky Blue Gloves Size M','Clinical & PPE','carton of 10 packs',45.00,'cliffyhill',50),
  ('igc-12353','wesley','Nitrile Sky Blue Gloves Size XL','Clinical & PPE','carton of 10 packs',45.00,'cliffyhill',10),
  ('igs-0090','wesley','INGO Cube Box Tissue','Housekeeping','carton of 100 boxes',60.00,'cliffyhill',5),
  ('igs-0400','wesley','IngoSoft Luxury Wrapped Toilet Pack','Housekeeping','pack of 50 rolls',33.00,'cliffyhill',70),
  ('igs-1200','wesley','IngoSoft Slimfold Paper Towels','Housekeeping','box of 20 bags',36.50,'cliffyhill',5),
  ('igs-1250','wesley','Matthews Interleave Toilet Tissue','Housekeeping','carton of 36 packs',33.87,'cliffyhill',180),
  ('wet-wipes','wesley','Wet wipes','Continence',null,19.00,'cliffyhill',35),
  ('mph-2050','wesley','Recycled Bin Liner 18L','Housekeeping','bag of 35 rolls',82.00,'cliffyhill',5),
  ('mph-2070','wesley','Recycled Bin Liner 36L','Housekeeping','bag of 29 rolls',88.00,'cliffyhill',5),
  ('mph-2360','wesley','Recycled Bin Liner 80L','Housekeeping','bag of 7 rolls',82.00,'cliffyhill',5),
  ('mph-30110','wesley','Medical Face Masks Type IIR','Clinical & PPE',null,50.00,'cliffyhill',115),
  ('mph-34720','wesley','A4 Print Paper','Other','carton',28.26,'cliffyhill',5),
  ('mph-38430','wesley','Matthews Lunch Napkins 500 sheet','Kitchen & Nutrition','carton of 6 bags',32.00,'cliffyhill',15),
  ('n95-mask','wesley','N95 Mask','Clinical & PPE','box',0.00,'cliffyhill',25),
  ('bsl-rubbish-bag-kitchen-2','wesley','BSL Rubbish Bag - Kitchen 2','Housekeeping',null,0.00,'cliffyhill',5),
  ('bsl-rubbish-bag-lge-bin-liner-kitchen-1','wesley','BSL Rubbish Bag LGE Bin Liner - Kitchen 1','Housekeeping',null,0.00,'cliffyhill',5),
  ('greenr-enzyme-all-purpose-cleaner','wesley','GreenR Enzyme All-Purpose Cleaner','Housekeeping','can',0.00,'cliffyhill',5),
  ('bioclean-odour-neutraliser','wesley','Bioclean Odour Neutraliser','Housekeeping','can',0.00,'cliffyhill',5),
  ('qualchem-saniclean-heavy-duty-cleaner-sanitiser','wesley','QualChem Saniclean Heavy Duty Cleaner Sanitiser','Housekeeping','can',0.00,'cliffyhill',5),
  ('alcohol-sanitiser-4l-75','wesley','Alcohol Sanitiser 4L 75%','Housekeeping','can',0.00,'cliffyhill',5),
  ('ap439-solution-5l','wesley','AP439 Solution 5L','Housekeeping','can',0.00,'cliffyhill',5)
on conflict (id) do update set name = excluded.name, category = excluded.category, unit = excluded.unit,
  price = excluded.price, provider_id = excluded.provider_id, par = excluded.par;

insert into public.stock_levels (product_id, building_id, qty_now) values
  ('grb2-5','wesley',0),
  ('grk4-20','wesley',4),
  ('grs4-5','wesley',3),
  ('grs6-5','wesley',5),
  ('grs8f-5','wesley',2),
  ('hipi','wesley',0),
  ('igc-0004','wesley',0),
  ('igc-0005','wesley',16),
  ('igc-0006','wesley',21),
  ('igc-0010','wesley',6),
  ('igc-0012','wesley',8),
  ('igc-0013','wesley',0),
  ('sanitary-pads','wesley',0),
  ('igc-12350','wesley',9),
  ('igc-12351','wesley',51),
  ('igc-12353','wesley',10),
  ('igs-0090','wesley',6),
  ('igs-0400','wesley',73),
  ('igs-1200','wesley',1),
  ('igs-1250','wesley',182),
  ('wet-wipes','wesley',39),
  ('mph-2050','wesley',5),
  ('mph-2070','wesley',7),
  ('mph-2360','wesley',0),
  ('mph-30110','wesley',119),
  ('mph-34720','wesley',0),
  ('mph-38430','wesley',18),
  ('n95-mask','wesley',26),
  ('bsl-rubbish-bag-kitchen-2','wesley',0),
  ('bsl-rubbish-bag-lge-bin-liner-kitchen-1','wesley',0),
  ('greenr-enzyme-all-purpose-cleaner','wesley',2),
  ('bioclean-odour-neutraliser','wesley',0),
  ('qualchem-saniclean-heavy-duty-cleaner-sanitiser','wesley',0),
  ('alcohol-sanitiser-4l-75','wesley',0),
  ('ap439-solution-5l','wesley',0)
on conflict (product_id, building_id) do update set qty_now = excluded.qty_now, updated_at = now();
